default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build the Android release bundle (AAB) without uploading"
  lane :build_release do
    gradle(task: "bundleRelease")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play (needs setup)"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
